### ISSUE TITLE
Switch to/from working_set by default

### ISSUE THREAD

**Issue by andyjessop** [coderifous/working_set#3]
When I do a search on a word, working_set picks that up and searches, but I'm still focussed on vim. I'd like it to switch immediately to working_set.

Likewise, when I hit `Enter` on a search, it effectively previews rather than focussing on the search result in vim. I almost never just want to preview, as I know the codebase well - I just want to be taken directly there.

I have working_set in a tmux pane next to my editor - what's the recommended way to achieve the above behaviour. Is it something that could be built into working_set?

**Comment by coderifous** [comment]
I also use Tmux and recommend  the [Tmux Navigator plugin](https://github.com/christoomey/vim-tmux-navigator.git) if you don't have that already.  It makes traversing vim and tmux panes consistent/seamless.  For me, this reduces the friction of switching the focus between Vim (in a tmux split on the left), and Working Set (in a tmux split on the right) when I want to do that.

With that said, I think you could achieve part of your desired behavior by mapping a custom vim binding that invokes the search (e.g. `:WSw <word under cursor>`) and then sends a signal to Tmux telling it to select the other pane (e.g. `tmux select-pane -t+`).

For the other direction, where you want to hit enter while the focus is in working_set and immediately have the focus go back to Vim: that would be less straightforward.  Working Set is not "tmux aware", and there's no way to extend behavior right now to say "when an item is selected, also do {action}".  However, the default {action} is for Working Set to send a signal to Vim, and Vim responds.  So you may be able to give yourself what you want by, again, customizing your Vim setup so that it runs something like `tmux select-pane -t${TMUX_PANE}` every time it calls [SyncLocation](https://github.com/coderifous/working-set.vim/blob/master/plugin/working-set-vim8.vim#L36).

**Comment by andyjessop** [comment]
That makes perfect sense, thanks. I've now got it set up with custom key bindings.
